### ISSUE TITLE
Crashes if Nmap is not installed or not in PATH

### ISSUE THREAD

**Issue by dmiller-nmap** [sheimo/nmapcli#2]
Your users will probably try to run this without installing Nmap, if the bug reports for the python-nmap library are any indication. You should first check that you can run Nmap before even displaying the menu, and let the user know to install it if it is not present.

**Comment by sheimo** [comment]
Hey Daniel,  I've been looking in to this.  I mainly started this project for the latest and greatest of kali just for use in my company.  I'm going to get things fixed up for other Linux users and add more features, I've just been busy. Thanks for the input!
